services:
    postgres:
        container_name: ddcocbot-postgres
        image: postgres:alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=ddcocbot
            - POSTGRES_PASSWORD=54f879079d2e4e852d83c727
            - POSTGRES_DB=ddcocbot
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:


networks:
    default: {}
