#
# Docker compose for ddcocbot arm64/aarch64
#

services:

  ddcocbot:
    image: debian:latest
    container_name: ddcocbot
    working_dir: /app
    volumes:
      - .:/app
    environment:
      # DATABASE CONNECTIVITY
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ddcocbot-database:5432/db_ddcocbot
      - SPRING_DATASOURCE_USERNAME=user_ddcocbot
      - SPRING_DATASOURCE_PASSWORD=password_ddcocbot
      - COC_API_URL=https://api.clashofclans.com/v1
      - COC_API_TOKEN=????
      - GROUP_LINK=????
      - CLAN=YPPQ9PUC
      - TELEGRAM-BOT_USERNAME=ddcocbot
      - TELEGRAM-BOT_TOKEN=????
    command: ["sh", "-c", "./ddcoc-1.0.5-arm64"]
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      ddcocbot-database:
        condition: service_healthy

  ddcocbot-database:
    image: 'postgres:17-alpine'
    container_name: ddcocbot-database
    environment:
      - POSTGRES_USER=user_ddcocbot
      - POSTGRES_PASSWORD=password_ddcocbot
      - POSTGRES_DB=db_ddcocbot
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_ddcocbot -d db_ddcocbot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:

